Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -68,35 +68,34 @@ jobs:
         path: coverage-report
 
   check-coverage:
-    runs-on: ubuntu-latest
-    needs: test
-    steps:
-    - name: Download coverage report
-      uses: actions/download-artifact@v3
-      with:
-        name: coverage-report
-        path: coverage-report
+      runs-on: ubuntu-latest
+      needs: test
+      steps:
+      - name: Download coverage report
+        uses: actions/download-artifact@v3
+        with:
+          name: coverage-report
+          path: coverage-report
 
-    - name: Verify coverage report existence
-      run: |
-        if [ ! -f "coverage-report/index.htm" ]; then
-          echo "Coverage report index.htm not found!"
-          exit 1
-        fi
+      - name: Verify coverage report existence
+        run: |
+          if [ ! -f "coverage-report/index.htm" ]; then
+            echo "Coverage report index.htm not found!"
+            exit 1
+          fi
 
-    - name: Extract coverage percentage from HTML
-      run: |
-        percentage=$(cat coverage-report/index.htm | grep -oP '<div class="large cardpercentagebar cardpercentagebar0">\K\d+(?=%)')
-        echo "Coverage percentage: $percentage%"
+      - name: Extract coverage percentage from HTML
+        run: |
+          percentage=$(cat coverage-report/index.htm | grep -oP '<div class="large cardpercentagebar cardpercentagebar0">\K\d+(?=%)')
+          echo "Coverage percentage: $percentage%"
 
-        if [ -z "$percentage" ]; then
-          percentage=0
-        fi
+          if [ -z "$percentage" ]; then
+            percentage=0
+          fi
 
-        if [ "$percentage" -lt 90 ]; then
-          echo "Test coverage is below 90%. Current coverage: $percentage%"
-          exit 1
-        else
-          echo "Test coverage is at or above 90%. Current coverage: $percentage%"
-        fi
-    
+          if [ "$percentage" -lt 90 ]; then
+            echo "Test coverage is below 90%. Current coverage: $percentage%"
+            exit 1
+          else
+            echo "Test coverage is at or above 90%. Current coverage: $percentage%"
+          fi
