Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -67,7 +67,7 @@ jobs:
         name: coverage-report
         path: coverage-report
 
-  check-coverage:
+    check-coverage:
     runs-on: ubuntu-latest
     needs: test
     steps:
@@ -79,16 +79,22 @@ jobs:
       with:
         dotnet-version: '8.0.205'
 
-    - name: List coverage-report directory
+    - name: Verify coverage-report directory
       run: |
-        echo "Listing contents of the coverage-report directory:"
-        ls -R coverage-report || echo "Coverage report directory not found!"
+        if [ ! -d "coverage-report" ]; then
+          echo "Coverage report directory not found!"
+          exit 1
+        else
+          echo "Coverage report directory found."
+        fi
 
     - name: Check if index.htm exists
       run: |
         if [ ! -f "coverage-report/index.htm" ]; then
           echo "Coverage report index.htm not found!"
           exit 1
+        else
+          echo "Coverage report index.htm found."
         fi
 
     - name: Extract and check coverage percentage
@@ -100,3 +106,4 @@ jobs:
         else
           echo "Test coverage is above 90%. Current coverage: $coverage_percentage%"
         fi
+
